name: Build & Deploy Preview

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload built bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dihor-cards-bundle
          path: dist/dihor-ha-components.js

      - name: Prepare preview directory
        run: |
          mkdir -p preview
          cp docs/demo.html preview/
          cp docs/demo.css preview/
          cp dist/dihor-ha-components.js preview/ || true
          cp src/cards/minecraft/*.html preview/
          cp src/cards/minecraft/*.css preview/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./preview
          publish_branch: gh-pages
          force_orphan: true
