name: Build & Deploy Preview

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare docs directory for GitHub Pages
        run: |
          mkdir -p docs/cards
          for dir in src/cards/*; do
            if [ -d "$dir" ]; then
              name=$(basename "$dir")
              mkdir -p docs/cards/$name
              cp "$dir"/*.html "$dir"/*.css docs/cards/$name/ || true
            fi
          done
          cp dist/dihor-ha-components.js docs/
          cp index.html docs/
          cp index.css docs/
          touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
