name: Publish to Beta

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build

      - name: Push bundle to beta branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git fetch origin beta
          git switch -C beta origin/beta || git switch --orphan beta

          cp dihor-cards-bundle.js ./
          git add dihor-cards-bundle.js
          git commit -m "Auto-publish from master"
          git push origin beta --force
